### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by nachocheezvartussin** [Borumer/Borum#15]
Borum is a cybersecurity project in essence. However, it is also an impactful website with a caring community. Web design is very important to any website, and the interface for Borum is lacking, to say the least. Attractive web design encourages viewers to see more of the site, and an easy and creative layout helps make the experience all that much better. Borum needs to have a more vibrant design, as well as a more unique layout. This would make the Q&A site a rival to, say, Quora's fantastic layout.

**Comment by varunsingh87** [comment]
@nachocheezvartussin I agree that Quora has an excellent design interface compared to the grayness of Borum.
I assign you the job of creating a Google Drawing for the Home Page to start off. This will include colors, shapes, and other design components, excluding buttons. Disregard the creation of any links and buttons. 
once you have made a rough sketch, publish it and paste the link here. Once you have finished this completely, **upload it to the repository** so it lies in the root directory. 
Of course, you are more than welcome to decline and another person such as I can do it. I will only assign the job to you if you are willing.

**Comment by nachocheezvartussin** [comment]
@KnowledgeableKangaroo Will do! I'll need some time to get my inspiration, and I'll be in contact when I'm ready to start.

**Comment by nachocheezvartussin** [comment]
![New Borum Interface](https://user-images.githubusercontent.com/51424701/59076381-c5bc2780-88a3-11e9-8478-5d4ed90d2ff6.jpg)
So, what do you think of the new and improved layout, and not to mention BORUM DARK MODE! This can be toggled in the profile settings, or can be kept as the traditional black on white.

**Comment by varunsingh87** [comment]
@nachocheezvartussin I have to say, you have exceeded my expectations with the colors, you have enticed me to add new features and images. The only thing I am unsure about is the fact that there is no additional content that you have added on the home page. 
I also don’t like the fact that there is no longer a sidebar but I will think about this during development.
Great design and keep up the outstanding work! Kudos!

**Comment by nachocheezvartussin** [comment]
Well, I thought I would leave the technical issues to you and just worry about converting it for now. You can feel free to add to the design if you decide to use it! Also, I personally think the sidebar is impractical, and the tabs at the top look much better.

**Comment by varunsingh87** [comment]
Okay, I will definitely get working on converting this new layout to code.

**Comment by KnowledgeableKangaroo** [comment]
Which one looks better?
![Screenshot (47)](https://user-images.githubusercontent.com/31084854/59388507-e966ee00-8d39-11e9-9911-ff4a2bee3ab0.png)
![Screenshot (48)](https://user-images.githubusercontent.com/31084854/59388508-e966ee00-8d39-11e9-99c6-e91224ae9d8d.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/51492381/59396225-b6325800-8d55-11e9-88a5-623ea30aac2d.png)
Like the new thing at the bottom and the added padding at the top?
I am still halfway through. See you at the finish!

**Comment by varunsingh87** [comment]
@nachocheezvartussin What is the font called?

**Comment by varunsingh87** [comment]
@nachocheezvartussin Is it Orbotron?

**Comment by nachocheezvartussin** [comment]
Yes it is, sorry for the late response @KnowledgeableKangaroo .

**Comment by ghost** [comment]
Alright, the interface issue has been resolved because I am not changnig the interface completely
