### ISSUE TITLE
Notification Bar

### ISSUE THREAD

**Issue by ghost** [Borumer/Borum#17]
I'm always frustrated when I have to check every part of the website in order to find whether somebody has replied to a post of mine or voted on it. I wish there was an easier way to check this.

Preferably, I would like a notification menu at the top which shows all answers to a question a logged in user posted and who voted what on any of his or her posts. This should link to that post's question page. The notifications could cover other things such as, in the future, if a topic proposal was approved, or somebody _commented_ on a post. The notification menu should appear as a bell, but when you click it, the menu pops up. Additionally, there should be a badge in the corner of the notification bell. This badge should tell the user how many unread notifications he or she has. 

An alternative solution would be to use email as the source of notifications. The problem with this, although it is more likely to alert them, may get annoying because lots of notifications at once

**Comment by ghost** [comment]
I am going to assign myself because I made the issue

**Comment by varunsingh87** [comment]
I would like you to start working on this issue now.
