### ISSUE TITLE
Post Deletion Redirecting Bug

### ISSUE THREAD

**Issue by nachocheezvartussin** [Borumer/Borum#21]
Description:
The bug occurs when a user deletes their post and clicks the confirmation button, and is then given a message that says "The post was successfully deleted. Redirecting you now..." However, the message does not trigger a redirection prompt, and leaves the user waiting until they realize they need to refresh the page.

1. Go to bforborum.com.
2. Log into user's account.
3. Click "Latest Questions". Alternatively, click "Ask a Question".
4. Click an existing question and write a comment on it. Alternatively, write a question and post it.
5. Click "delete" under the comment and confirm deletion. Alternatively, click "delete" under the question and confirm deletion.
6. See bug,

Expected Behavior:
The expected result is a redirection from the deletion screen back to the "Home" page or the  "Latest Questions" page.

Screenshot:
![image](https://user-images.githubusercontent.com/51424701/59316215-4e173f80-8c8b-11e9-9bad-212a78fc5673.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows
 - Browser Google Chrome
 - Versions:
 Microsoft Windows: Version 1903 
 Google Chrome: Version 72.0.3626.121

**Comment by varunsingh87** [comment]
I am assigning my co-worker, GnatSwatter to get working on it.

**Comment by nachocheezvartussin** [comment]
@KnowledgeableKangaroo Great. Hope to see it soon, ask me if you need any help!

**Comment by KnowledgeableKangaroo** [comment]
![image](https://user-images.githubusercontent.com/31084854/59396179-7ff4d880-8d55-11e9-8d40-b25ef77e629e.png)

**Comment by ghost** [comment]
Cool, I am going to get working on this.

**Comment by ghost** [comment]
I am working on this right now and it will be resolved by the end of my coding session tonight.

**Comment by ghost** [comment]
Finally fixed it!
