### ISSUE TITLE
cant use search function to search users

### ISSUE THREAD

**Issue by nachocheezvartussin** [Borumer/Borum#36]
You can't use the search function to search for Borum users.

1. Go to bforborum.com
2. Click on search bar
3. Type in name of a user

You are supposed to be able to search for a viewer.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 78.0.3904.70

**Comment by varunsingh87** [comment]
Hi @nachocheezvartussin, thanks for taking the time to report this bug. I have assigned GnatSwatter to look into the bug.

**Comment by ghost** [comment]
@nachocheezvartussin Hi! Searching for users is not the functionality of the search bar, rather searching for messages. In the future, there will be a search bar on the users page. I will leave the issue open until then.
 Feel free to send designs for what the new users page can look like - as well as a mobile version.
