### ISSUE TITLE
email verification doesn't work

### ISSUE THREAD

**Issue by nachocheezvartussin** [Borumer/Borum#37]
When checking the emailed account verification for Borum, the accompanying verification link doesn't work.

1. Go to bforborum.com
2. Click on sign up and create an account
3. Check inputted email's "spam" category
4. Open Borum verification link
5. See error

The verification link is supposed to appear in the email to be able to verify the account,

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 78.0.3904.70

**Comment by varunsingh87** [comment]
This seems quite strange
