### ISSUE TITLE
Error message for trying to comment while not signed in

### ISSUE THREAD

**Issue by nachocheezvartussin** [Borumer/Borum#42]
When you are not signed into your Borum account, you can still view topics started by other users. But, the commenting feature is supposedly disabled. When you try to comment while not signed in, nothing happened. This can be quite confusing for some users.

The console should give an error message prompting the user to sign in before commenting when clicking the comment button while not signed in.

**Comment by varunsingh87** [comment]
Hey @nachocheezvartussin what do you mean by comment? Could you please be more specific about topics, comments, and add a few screenshots? Thanks.

**Comment by varunsingh87** [comment]
@nachocheezvartussin There is already functionality for this
