### ISSUE TITLE
Search bar for questions

### ISSUE THREAD

**Issue by varunsingh87** [Borumer/Borum#6]
Most Q & A Website that are popular, secure, and trusted have a search bar at the top. Borum should also be a website with a search bar at the top on the **Latest Questions** page that searches for the questions. A starter for this should be, that when they press enter, it sends what they typed to the url as a query string, and then this is accessed using `$_GET` to be injected into an SQL statement (after everything is sanitized) using BOOLEAN FULLTEXT search.

**Comment by varunsingh87** [comment]
In rpgoress - making space at the top

**Comment by ghost** [comment]
FULLTEXT indexes shouldn't be put on columns that are inserted and updated

**Comment by varunsingh87** [comment]
@GnatSwatter I think it is worth it because there would be no other way for the search bar to work
